SW1:
  username: '11'
  hostname: 192.168.56.11
  password: 2005qazwsx
  connection_options:
    netmiko:
      extras:
        device_type: hp_comware
        port: 22
  data:
    vendor: HCLCloud
SW2:
  username: '12'
  hostname: 192.168.56.12
  password: 2005edcrfv
  connection_options:
    netmiko:
      extras:
        device_type: hp_comware
        port: 22
  data:
    vendor: HCLCloud
SW3:
  username: '13'
  hostname: 192.168.56.13
  password: tgbyhn
  connection_options:
    netmiko:
      extras:
        device_type: hp_comware
        port: 22
  data:
    vendor: HCLCloud
SW4:
  username: '14'
  hostname: 192.168.56.14
  password: 2005ujmiko
  connection_options:
    netmiko:
      extras:
        device_type: hp_comware
        port: 22
  data:
    vendor: HCLCloud
SW5:
  username: '15'
  hostname: 192.168.56.15
  password: 2005okmijn
  connection_options:
    netmiko:
      extras:
        device_type: hp_comware
        port: 22
  data:
    vendor: HCLCloud
SW6:
  username: '16'
  hostname: 192.168.56.16
  password: 2005uhbygv
  connection_options:
    netmiko:
      extras:
        device_type: hp_comware
        port: 22
  data:
    vendor: HCLCloud
'5555':
  username: admin
  hostname: 192.168.58.5
  password: '154235'
  connection_options:
    netmiko:
      extras:
        device_type: huawei
        port: 22
  data:
    vendor: 华为Huawei
